[package]
name = "server"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "The server of Border Wars"
repository = "https://git.tipragot.fr/corentin/border-wars.git"

# [lints]
# workspace = true
